# Generated by Django 2.0 on 2020-11-24 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0002_readdetaill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetaill',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='时间'),
        ),
    ]
