# Generated by Django 2.0 on 2020-11-24 13:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20201124_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 13, 6, 9, 507379, tzinfo=utc), verbose_name='时间'),
        ),
    ]
